# Generated by Django 2.2.12 on 2020-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=128)),
                ('signal_name', models.CharField(max_length=255)),
                ('signal_type', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'signalcontrol',
            },
        ),
    ]
