# Generated by Django 2.2.12 on 2020-04-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_signalcontrol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signalcontrol',
            unique_together={('app_name', 'model_name', 'signal_name')},
        ),
    ]
